export const getEventEmoji = (title: string, type: string) => {
  const titleLower = title.toLowerCase();
  
  // Specific activity emojis - all different and unique
  if (titleLower.includes('shabbos')) return '🕯️';
  if (titleLower.includes('tzfat') || titleLower.includes('tzfas')) return '🏔️';
  if (titleLower.includes('wall') || titleLower.includes('kotel')) return '🕊️';
  if (titleLower.includes('museum')) return '🏛️';
  if (titleLower.includes('market') || titleLower.includes('shuk')) return '🛒';
  if (titleLower.includes('beach') || titleLower.includes('eilat')) return '🏖️';
  if (titleLower.includes('hike') || titleLower.includes('hiking')) return '🥾';
  if (titleLower.includes('yurts') || titleLower.includes('overnight')) return '⛺';
  if (titleLower.includes('old city')) return '🏰';
  if (titleLower.includes('flight') || titleLower.includes('travel')) return '✈️';
  if (titleLower.includes('pool') || titleLower.includes('swim')) return '🏊';
  if (titleLower.includes('meal') || titleLower.includes('dinner')) return '🍽️';
  if (titleLower.includes('tour')) return '🚌';
  if (titleLower.includes('activity')) return '🎯';
  if (titleLower.includes('masada')) return '🏜️';
  if (titleLower.includes('dead sea')) return '🌊';
  if (titleLower.includes('golan')) return '⛰️';
  if (titleLower.includes('rafting')) return '🛶';
  if (titleLower.includes('chocolate')) return '🍫';
  if (titleLower.includes('paintball')) return '🎨';
  if (titleLower.includes('archery')) return '🏹';
  if (titleLower.includes('donkey')) return '🦙';
  if (titleLower.includes('snorkeling')) return '🤿';
  if (titleLower.includes('scuba')) return '🤿';
  if (titleLower.includes('glass')) return '🪟';
  if (titleLower.includes('dig')) return '⛏️';
  if (titleLower.includes('atv')) return '🏎️';
  if (titleLower.includes('boat')) return '⛵';
  if (titleLower.includes('sailing')) return '⛵';
  if (titleLower.includes('bonfire')) return '🔥';
  if (titleLower.includes('smores')) return '🍫';
  if (titleLower.includes('kumzits')) return '🎵';
  if (titleLower.includes('learning')) return '📖';
  if (titleLower.includes('shiur')) return '📚';
  if (titleLower.includes('davening')) return '🙏';
  if (titleLower.includes('kiddush')) return '🍷';
  if (titleLower.includes('fabrengen')) return '🎉';
  if (titleLower.includes('orientation')) return '📋';
  if (titleLower.includes('welcome')) return '👋';
  if (titleLower.includes('boys start')) return '🚀';
  if (titleLower.includes('boys end')) return '🏁';
  if (titleLower.includes('camp day')) return '🏕️';
  if (titleLower.includes('chill day')) return '😌';
  if (titleLower.includes('talent show')) return '🎭';
  if (titleLower.includes('improv')) return '🎪';
  if (titleLower.includes('dodgeball')) return '⚾';
  if (titleLower.includes('capture the counselor')) return '🎯';
  if (titleLower.includes('banana boating')) return '🍌';
  if (titleLower.includes('fear factor')) return '😱';
  if (titleLower.includes('stomp')) return '👟';
  if (titleLower.includes('water sports')) return '🏄';
  if (titleLower.includes('ice mall')) return '❄️';
  if (titleLower.includes('dolphins')) return '🐬';
  if (titleLower.includes('bbq')) return '🍖';
  if (titleLower.includes('pizza')) return '🍕';
  if (titleLower.includes('sushi')) return '🍣';
  if (titleLower.includes('forest walk')) return '🌲';
  if (titleLower.includes('nap')) return '😴';
  if (titleLower.includes('natural spring')) return '💧';
  if (titleLower.includes('cave')) return '🕳️';
  if (titleLower.includes('haunted house')) return '👻';
  if (titleLower.includes('blind museum')) return '🕶️';
  if (titleLower.includes('nova festival')) return '🎪';
  if (titleLower.includes('memorial')) return '🕊️';
  if (titleLower.includes('sderot')) return '🏘️';
  if (titleLower.includes('yad v\'shem')) return '🕯️';
  if (titleLower.includes('tisha bav')) return '🕊️';
  if (titleLower.includes('hidden waterfall')) return '🌊';
  if (titleLower.includes('black canyon')) return '🏔️';
  if (titleLower.includes('party boat')) return '🎉';
  if (titleLower.includes('grape harvest')) return '🍇';
  if (titleLower.includes('red canyon')) return '🏜️';
  if (titleLower.includes('timna park')) return '🏞️';
  
  // Type-based fallback emojis - all different from activity emojis
  switch (type) {
    case 'spiritual': return '🙏';
    case 'adventure': return '⛰️';
    case 'educational': return '📚';
    case 'leisure': return '☕';
    case 'travel': return '🚐';
    case 'cultural': return '🎨';
    default: return '📅';
  }
}; 